export { default as Movie } from "./Movie";
export { default as Actor } from "./Actor";
export { default as Director } from "./Director";
export { default as MovieDetails } from "./MovieDetails";
export { default as User } from "./User";
export { default as UserReview } from "./UserReview";
export { default as ActorRoleMovie } from "./ActorRoleMovie";
export { default as Trailer } from "./Trailer";
export { default as MovieRating } from "./MovieRating";
