export const ApiUrl = {
  login: '/auth/login',
  signUp: '/auth/signup',
  getDirector: '/directors',
  getDirectorByName: '/directors/getByName',
  getActor: '/actors',
  getActorByName: '/actors/getByName',
  updateMovie: '/upload/',
  trailers: '/trailers',
  user: '/user',
  vote: '/user/vote',
  unVote: '/user/unVote',
  addToWatchList: '/user/addToWatchList',
  removeFromWatchList: '/user/removeFromWatchList',
  movies: '/movies',
  movieList: '/movies/list',
  moviesByPage: '/movies/getByPage',
  homeData: '/homeData',
  findAllDataType: '/mixData',
};
